### ISSUE TITLE
RawClusters and RawTowers missing single unique identifiers

### ISSUE THREAD

**Issue by mccumbermike** [sPHENIX-Collaboration/coresoftware#16]
The jet clustering algorithms need unique identifiers to keep track of what is in the jet. RawClusters are missing proper unique identifiers (and RawTowers have two ids instead of one). We have branch with new calorimeter objects, so we wait for those to merge to solve this problem or should we add unique identifiers to these possibly-soon-to-be legacy objects? Will that branch also bring in a new CaloCluster Object?

**Comment by nfeege** [comment]
Yes, the new branch will eventually have a new CaloCluster object to account for the new CaloTower objects having only one identifier, for example. I'm not sure yet how long it will take to get all the new tower geometry, mapping, clustering, ... in in place for this branch so that we can reliably switch to it. I'm working on it, but if you need those clusters soon, I would suggest to patch the RawClusters with some unique identifier.

**Comment by blackcathj** [comment]
A patch with unique identifier to the current tower object sounds attractive to me too. Also it may make the transition to the next version of tower easier, since a unique identifier will be required there too.

**Comment by pinkenburg** [comment]
it should be easy to change the current tower class - the unique 
identifier can be constructed from the eta and phi bin by just 
bitshifting one of them and return the result as identifier. Or we can 
use that as unique identifier and extract the eta/phi bin on the fly.. 
We said 8 bits for the calorimeter id and 24 for the tower id, 12 bits 
for eta and 12 for phi should be sufficient. That scheme can be taken 
over by the new tower class.


On 8/7/2015 12:21 AM, Jin Huang wrote:
> A patch with unique identifier to the current tower object sounds attractive to me too. Also it may make the transition to the next version of tower easier, since a unique identifier will be required there too.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sPHENIX-Collaboration/coresoftware/issues/16#issuecomment-128593005

-- 
*************************************************************

Christopher H. Pinkenburg	;    pinkenburg@bnl.gov
				;    http://www.phenix.bnl.gov/~pinkenbu

Brookhaven National Laboratory	;    phone: (631) 344-5692
Physics Department Bldg 510 C	;    fax:   (631) 344-3253
Upton, NY 11973-5000

*************************************************************

**Comment by nfeege** [comment]
I second Chris' suggestion of using 12 bits for eta and 12 bits for phi (partially because that's also how I just defined a tower ID for the forward HCAL with the j and k index we had been using there instead of eta and phi). The only thing that came to my mind: Do we want to reserve a few bits to allow for a longitudinal segmentation of a tower within a given calorimeter? If not, yes, 8 calorimeter id, 12 eta bin, 12 phi bin is good.

**Comment by mccumbermike** [comment]
Since the consensus was to patch the old objects gone ahead and done that. For the towers I've reported ((bineta << 12)|(bin phi)) as the unique id. This is done in RawTowerv1. Please modify if you want the 8 bits of calorimeter id filled as well or if I chosen the eta/phi bit ranges backward. For the clusters these just pick up the key from the storage map on entry. Merge forthcoming.
