### ISSUE TITLE
cemc prototype generates different hits when compiling without optimizer

### ISSUE THREAD

**Issue by pinkenburg** [sPHENIX-Collaboration/coresoftware#199]
During the testing of the modified hcal I came across an issue for the cemc prototype. For debugging purposes I had compile g4detectors without optimization which doesn't affect the results for the hcals. But the cemc results are not identical. My assumption is that it is the reading of the xml calibration file which has this hokey double printouts. Alternatively a mix of floats and doubles can cause this behavior. In any case this behavior points to an issue and at least makes debugging code a lot harder

**Comment by blackcathj** [comment]
For the newest SPACAL software, https://github.com/sPHENIX-Collaboration/coresoftware/pull/300, checked against non-optimized-build with flag ```CXXFLAGS="-g -O0 -std=c++11 -Wall -Werror"```. The result Hash check for ```PHG4Parameter``` read back is identical (```Geometry_2017ProjTilted/cemc_geoparams-0-0-4294967295-1495405153.xml``` has Hash of 0xbca61e72ef2d5217). And the result shower with same random seed is also identical (Hash of QA distributions.). Therefore this issue seems resolved now.
