### ISSUE TITLE
segfault in jet evaluator for hijing hits files

### ISSUE THREAD

**Issue by pinkenburg** [sPHENIX-Collaboration/coresoftware#44]
using the standard Fun4All_G4_sPHENIX.C macro with readhits=true and the input file
/gpfs02/phenix/prod/sPHENIX/preCDR/pro.1-beta.3/sHijing/spacal2d/G4Hits_sPHENIX_sHijing-0-4.4fm_0000.root
It crashes in
JetTruthEval.C:63
with the truthjet being a null pointer.

**Comment by mccumbermike** [comment]
I found a few hours ago a limitation in the tracking and calorimeter evaluator when there is more than one vertex in phg4truthinfo. This was based on my misunderstanding of the PHG4TruthInfo storage where I had to guess at what was stored on what map and when---I think I understand that now. The jet eval has a similar problem, but there it seems I will need to store the indexes of secondary and primary truth particles separately since the tracing should be done on different maps.

**Comment by mccumbermike** [comment]
I'm pretty

**Comment by mccumbermike** [comment]
Sorry finger slipped. The new pull request should resolve this issue. Let me know if it does not.

**Comment by mccumbermike** [comment]
There is still a problem with the latest new build. I'm looking into it this morning.

**Comment by mccumbermike** [comment]
I still need to work on the TPC branch eval to bring that under eval support---I'll be doing this very soon now---but the default detector config is running well for the jet eval to the extent that I can test as of commit aaf394a. Closing issue.
