### ISSUE TITLE
index bug in simulation/g4simulation/g4hough/SvtxVertex_v1.C

### ISSUE THREAD

**Issue by pinkenburg** [sPHENIX-Collaboration/coresoftware#94]
I ran insure over a single particle simulation and it seems to have discovered an out of bounds problem in this code. In the ctor it initializes by

  for (int j = 0; j < 3; ++j) {
    for (int i = j; i < 3; ++i) {
      set_error(i,j,NAN);
    }
  } 

set_error sets variables in _err which is _err[3]
void SvtxVertex_v1::set_error(unsigned int i, unsigned int j, float value) {
  _err[covar_index(i,j)] = value;
  return;
}

The index is calculated in covar_index:
unsigned int SvtxVertex_v1::covar_index(unsigned int i, unsigned int j) const {
  if (i>j) std::swap(i,j);
  return i+1+(j+1)*(j)/2-1;
}
If I take the pair of parameters where insure complains (i=0, j=2) covar_index returns 3 which is off by one:

#include <iostream>

using namespace std;

int main()
{
  int i = 0;
  int j = 2;
  if (i>j) std::swap(i,j);
  int k =  i+1+(j+1)*(j)/2-1;
  cout << "k: " << k << endl;
  return 0;
}

**Comment by mccumbermike** [comment]
Good catch. This is a packed array for the covariance matrix. It seems when I cut and pasted from a 2x2 example, I forgot to increase the dimensions for the 3x3 covariance, but we aren't yet filling the covariance so no run-time error was generated. Fixed by commit 31425b7fc3d0171e124a932c4e5a12adb0f338f8.
